### ISSUE TITLE
Can the model maintain the original accuracy when the BPSK modulation is cancelled?

### ISSUE THREAD

**Issue by xingchen0120** [yoniLc/ECCT#2]
Hi,
Can the model maintain the original accuracy when the BPSK modulation is cancelled?  If accuracy can be maintained, how should I rewrite the code?
How could I generate a new verification matrix for BCH code, for example, code_n=127,code_k=106.

Thanks

**Comment by yoniLc** [comment]
The model can work under different modulations. Removing the BPSK should work but will obviously decrease the performance since you use less energy for the transmission. 

I am not sure what you mean by verification matrix, but I am not providing here solutions for the creation of a desired BCH parity check matrix (can be done with polynomials though).
